
name: Release

on:
  release:
    types: [created]
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: |
        sed -i "s/version = '0.0.0'/version = '${{ github.event.release.tag_name }}'/" pyproject.toml
        python -m build
    - name: Publish package using Trusted Publishing
      uses: pypa/gh-action-pypi-publish@release/v1
